version: '3'

services:
  traefik:
    image: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
  whoami:
    container_name: whoami
    image: emilevauge/whoami
  whoami2:
    container_name: whoami2
    image: emilevauge/whoami
    command: "sh sleep 1000"
  static:
    container_name: static
    image: trinitronx/python-simplehttpserver
    volumes:
      - ./static:/var/www:ro
  gravis:
    container_name: gravis
    image: trinitronx/python-simplehttpserver
    volumes:
      - ../gravis:/var/www:ro
  proxy:
    container_name: proxy
    image: johnsparger/cors-anywhere
    # expose:
    #   - "8080"
